package com.acs.models.statics;

public enum RoadType {

    FOOTWAY, PATH, SERVICE, PEDESTRIAN, RESIDENTIAL, PRIMARY, SECONDARY, CYCLEWAY, TERTIARY, PLATFORM, LIVING_STREET, ROAD,
    STEPS, PRIMARY_LINK, SECONDARY_LINK, TRACK, TRUNK, TRUNK_LINK, TERTIARY_LINK, PROPOSED,  OTHER, CONSTRUCTION, BUS_STOP, UNCLASSIFIED, UNKNOWN
}
