package com.acs.models.statics;

public enum RoadType {

    FOOTWAY, PATH, SERVICE, PEDESTRIAN, RESIDENTIAL, PRIMARY, SECONDARY, CYCLEWAY, TERTIARY, PLATFORM, LIVING_STREET,
    STEPS, PRIMARY_LINK, SECONDARY_LINK, TRACK, TRUNK, TRUNK_LINK, OTHER, CONSTRUCTION, UNCLASSIFIED, UNKNOWN
}
